on:
  pull_request:
    types:
      - opened

jobs:
  pr-actions:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Post PR Comment
        uses: madsporse/github-actions-docker-giphy-pr@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
      
      - name: Post JS Action PR Comment
        uses: madsporse/github-actions-js-giphy-pr@1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          giphy-api-key: ${{ secrets.GIPHY_API_KEY }}