on:
  pull_request:
    types:
      - opened

jobs:
  pr-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Post PR Comment
        uses: madsporse/github-actions-docker-giphy-pr@main
        with:
          # github-token: automatically available (native GitHub secret)
          # the "permissions" above are used to assign permissions to this token
          # giphy-api-key: get from the Giphy Developers portal
          github-token: ${{ secrets.GITHUB_TOKEN }}
          giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
